[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "assist-genie"
version = "0.1.0"
description = "Assist Genie project dependencies"
authors = [name ="Shray Sinha", email="shray.sinha@llb.com"]
maintainers = [name ="Shray Sinha", email="shray.sinha@llb.com"]

[tool.poetry.dependencies]
python = ">=3.8"
fastapi = "^0.100.0"
uvicorn = "^0.22.0"
langchain = "^0.0.1"
PyPDF2 = "^3.0.0"
chromadb = "^0.4.0"
tiktoken = "^0.4.0"
google-generativeai